services:
  odoo19-community-db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo19-community-pg-data:/var/lib/postgresql/data

  odoo19-community:
    image: odoo:19.0
    depends_on:
      - odoo19-community-db
    ports:
      - "8090:8069"
    environment:
      - HOST=odoo19-community-db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo19-community-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
volumes:
  odoo19-community-web-data:
  odoo19-community-pg-data:
