[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

admin_passwd = admin123

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

workers = 5
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 1200
limit_time_real = 2400
